dmlc/MXNet.jl

README.md
This path separator will now work on Windows; instead,  you can pass variable number of arguments to `Pkg.dir`, which automatically does `joinpath` for the arguments.
=> fix the sample code in README

docs/api/initializer.rst, docs/api/io.rst, docs/api/symbolic-node.rst, src/initializer.jl
Following the discussion in https://github.com/dmlc/mxnet/pull/610 I took another swing at Xavier.
The idea is that the concepts proposed in the papers [1, 2, 3] can be generalized in choosing the regularization factor `1/fan_in` `1/fan_out` `2/(fan_out + fan_in)`, the distribution to sample from and a magnitude scaling factor. [1] proposes `3/fan_in` and `6/(fan_out+fan_in)` and [2,3] propose `2/fan_in`. 
[1] X. Bengio and Y. Glorot (2010) http://jmlr.csail.mit.edu/proceedings/papers/v9/glorot10a.html
[2] K. He, X. Zhang, S. Ren, and J. Sun (2015) http://arxiv.org/abs/1502.01852
[3] A. M. Saxe, J. L. McClelland, and S. Ganguli (2013/2014) http://arxiv.org/abs/1312.6120v3
=> Rework Xavier to be more flexibility

src/symbolic-node.jl, test/unittest/symbolic-node.jl
In response to https://github.com/dmlc/mxnet/pull/685/
I suppose we would want as API:
````julia
mx.Data(name=:data, attributes = Dict(:key, "value"))
````
=> basic interface for setting and getting attributes

docs/api/io.rst, docs/api/ndarray.rst, docs/api/symbolic-node.rst, src/symbolic-node.jl, test/unittest/symbolic-node.jl
Follow up on #35.
I went with the Nullable abstraction, because we don't have `haskey` and it encapsulates what is happening underneath. 
@pluskid Where would the right place to document this be?
=> attr interface for SymbolicNodes

src/model.jl
https://github.com/dmlc/mxnet/pull/717 a PR upstream added `floor`/`ceil`/`round,` which are now imported as operators, causing problems with the native Julia functions. Luckily there is only one usage.
=> Fixes usuage of floor

src/MXNet.jl, src/model.jl
Its probably better to import these explicitly so that multiple-dispatch can take care of it.
=> imports operators into the namespace to prevent issues

src/io.jl, src/model.jl
This fix two errors in the test process:
ERROR: LoadError: LoadError: MethodError: `min` has no method matching min(::Int64, ::Int64)
you may have intended to import Base.min
in next at /home/x/.julia/v0.4/MXNet/src/io.jl:438
in test_arrays_shuffle at /home/x/.julia/v0.4/MXNet/test/unittest/io.jl:107
in include at ./boot.jl:261
in include_from_node1 at ./loading.jl:304
in anonymous at /home/x/.julia/v0.4/MXNet/test/runtests.jl:10
in map_to! at abstractarray.jl:1286
in map at abstractarray.jl:1308
in test_dir at /home/x/.julia/v0.4/MXNet/test/runtests.jl:9
in include at ./boot.jl:261
in include_from_node1 at ./loading.jl:304
in process_options at ./client.jl:280
in _start at ./client.jl:378
while loading /home/x/.julia/v0.4/MXNet/test/unittest/io.jl, in expression starting on line 120 …
=> Fix compilation errors for julia 0.4.2

src/executor.jl
This is handy to get an estimate of how much temp_space is going to be allocated for a network.
=> add function to get debug_str, similar to python

src/model.jl
The TempSpace reported by MXNet is a good estimation to have when model sizes get to big for your GPU. `nvidia-smi` only reports successful allocation and as such is not helping with that.
The only problem is that this estimate is missing something since during runs, nvidia-smi reports more than double the memory usage.
=> Output temp space

docs/api/io.rst, docs/api/metric.rst, docs/api/ndarray.rst, docs/api/symbolic-node.rst, src/metric.jl
I was reading the code in metric.jl again and I couldn't understand my own implementation of Accuracy anymore. So I rewrote it to be more obvious to what it does, but it is slightly less general.
Additionally this adds the average cross-entropy measure or logloss measure for multidimensional softmax.
=> Refactor multi-dimensional accuracy measure and add average cross-entropy

deps/build.jl, deps/cblas.h
This PR removes the Linux package-managing stuff requiring users to install `libcblas`.  We know Julia already comes with `libopenblas`, and as there is no real reason I can think of to use `libcblas` over `libopenblas`, I suggest this change as it makes things easier and doesn't cause potential conflicts with systems that already have a BLAS library installed.
What do you think?
=> Use openblas from Julia, instead of installing yet another BLAS library

src/executor.jl, src/model.jl, src/symbolic-node.jl, test/unittest/symbolic-node.jl
Setting `attrs = Dict(:grad => "freeze")` on a layer causes it to be ignored in the when updating the weights.
We probably can make this a bit more efficient by setting grad_req=GRAD_NOP in bind for these layers.
This depends on https://github.com/dmlc/mxnet/pull/1965 and fixes #63.
=> [RFC] Freeze layers

src/util.jl
Added try catch around the unzip and added `7z` extraction alternative.
If Julia is added to the path, `7z` will be present in the path. `unzip` is not present on windows which caused the `IO::MNIST` to fail.
Added try/catch around the run expressions with an error message about no extraction utility on path.
=> Added 7z alternative for mnist allowing test to run on windows

src/symbolic-node.jl
Where `set_attr` was originally called in
`_define_atomic_symbol_creator` would cause `list_attr` to return a
dictionary with extra bias and weight fields as seen here: `
Dict{Symbol,ByteString}(:convolution0_a=>"a",:convolution0_π=>"π",:convolution0_bias_a=>"a",:convolution0_weight_π=>"π",:convolution0_bias_π=>"π",:convolution0_weight_a=>"a",:data2_test=>"hallo!")`
The return now is:`Dict{Symbol,ByteString}(:convolution0_a=>"a",:convolution0_π=>"π",:data2_test=>"hallo!")`
The test still fails however as `list_attr` still contains the name of
the source before the key.
Unsure whether the tests need to be changed to reflect the current return symbols or whether `list_attr` should be modified to try and strip the name information from the keys.
=> Change where set_attr is called in _define_atomic_symbol_creator

src/metric.jl
MXNet allows for the design of networks that use the same label for multiple outputs. Instead of failing for these kinds of networks, warn the user and try to proceed.
The correct fix would be to keep track of which label belongs to which output, but currently we lose that kind of mapping.
@pluskid I was wondering after looking through `fit`, would you be open to a refactor of MXNet.jl to use `Dict{Symbol, NDArray}` instead of `Vector{NDArray}`?
This would also be helpful in cases like https://github.com/dmlc/MXNet.jl/blob/9880bdf57b350b2602684446d3bfe0f3a2a0094b/src/executor.jl#L149-L152 , where we need to create `NDArray` for non-existing gradients to not confuse the indexing in `fit`.
=> Deduplicate and generalise metric update!

src/ndarray.jl, src/symbolic-node.jl, test/unittest/bind.jl, test/unittest/ndarray.jl, test/unittest/operator.jl
MXNet and mshadow support a range of different types. The Julia backend currently only works with Float32 and so I am hoping to extend it to support all types supported in the backend.
@pluskid Should we convert `NDArray` to `NDArray{T}` so that we get typestable methods? e.g. `getindex`...
=> [WIP/RFC]Type support for NDArray

.travis.yml, deps/build.jl, src/base.jl, src/callback.jl, src/executor.jl, src/io.jl, src/kvstore.jl, src/model.jl, src/ndarray.jl, src/symbolic-node.jl, src/util.jl
Since I last updated the Julia bindings in preparation for the release v0.5 there where a bunch of changes with regards of handling `Cstring`. This fixes almost all deprecation while keeping support for v0.4.
At some point we should go through all `unsafe_wrap` and `unsafe_string` methods to establish who is responsible to free the memory associated with the pointer. Currently the assumption is in most cases that these pointers are going to be freed-ed by MXNet proper. 
Once we switch to only support v0.5 9e9c490 should be reverted and thus removing the last warnings.
Lastly this also contains some cleanup with regards to formatting of documentations, but we were also overwriting docs accidentally and I need to find a way to do this properly (v0.5 only).
=> Get MXNet.jl ready for v0.5

docs/src/tutorial/mnist.md, docs/src/user-guide/overview.md, src/callback.jl, src/context.jl, src/executor.jl, src/initializer.jl, src/io.jl, src/metric.jl, src/model.jl, src/ndarray.jl, src/nn-factory.jl, src/optimizer.jl, src/symbolic-node.jl, src/visualize.jl
This removes remnant `:class` and `` throughout the docs. We will need to remove a few more RST stuff, but as an example the `note` blocks can be replaced by `!!! note` and we could have something similar for warnings.
We should also take a look at https://github.com/JuliaDocs/DocStringExtensions.jl
=> Cleanup `` and :class:

.travis.yml, docs/make.jl, docs/src/api/io.md, src/base.jl, src/io.jl, src/ndarray.jl, src/symbolic-node.jl
This improves the doc situation for `io.jl`. There might be a problem with `@autodocs` and `@docs` that needs to be solved in Documenter (I am still investigating).
=> reorder docs for io.jl and bring them into the markdown age

src/symbolic-node.jl
I was looking at http://stackoverflow.com/questions/35840176/how-to-get-a-gradient-node-with-mxnet-jl-and-julia# and we were not exposing `SymbolGrad`.
I was wondering what `compile` meant in the python api, but it seems to no longer exist? https://github.com/dmlc/mxnet/issues/3157
=> add grad function to do autodiff

docs/src/api/optimizer.md, docs/src/api/optimizers/adam.md, docs/src/api/optimizers/sgd.md, src/callback.jl, src/executor.jl, src/model.jl, src/ndarray.jl, src/nn-factory.jl, src/optimizer.jl, src/optimizers/adam.jl, src/optimizers/sgd.jl, src/symbolic-node.jl, src/util.jl, src/visualize.jl
=> cleanup docs a bit more

src/ndarray.jl, src/symbolic-node.jl, test/unittest/ndarray.jl
this fixes #120 
This is similar to how python handles things, but it doesn't allow us to handle miss-typed kwargs gracefully.
@pluskid For transpose we might need to do some more work, since the expected order and axis's ids are in python order and not Julia order (thus backwards...)
=> handle kwargs for ndarray functions

src/io.jl
This attempts to provide some documentation of the `mx.eachbatch` method defined for every data provider.
=> Add some docs to `eachbatch`

docs/src/api/optimizer.md, examples/mnist/mlp-test.jl, src/optimizer.jl, src/optimizers/adadelta.jl, src/optimizers/adagrad.jl, src/optimizers/adam.jl, src/optimizers/adamax.jl, src/optimizers/nadam.jl, src/optimizers/rmsprop.jl
Implemented some new optimizers, as was requested in [https://github.com/dmlc/MXNet.jl/issues/11](https://github.com/dmlc/MXNet.jl/issues/11)
* AdaDelta
* AdaGrad
* AdaMax
* RMSProp
* Nadam
Also, made slight change in ADAM code, as written in [https://arxiv.org/pdf/1412.6980v8.pdf](https://arxiv.org/pdf/1412.6980v8.pdf): "Note that the efficiency of algorithm 1 can, at the expense of clarity, be improved upon by changing the order of computation, e.g.  by replacing the last three lines in the loop"
New optimizers can be tested in examples/mnist/mlp-test.jl
=> New Optimizers

src/symbolic-node.jl
This is a fix of a bug, that was masked by 3 years old bug in Julia. For references, see:
* https://github.com/JuliaLang/julia/issues/14893
* https://github.com/JuliaLang/julia/pull/15850
* https://github.com/JuliaLang/julia/issues/19587
This change do not affect julia 0.4 and 0.5, but remove one of the errors in julia 0.6.
=> Fix hygiene bug

src/model.jl
I realized that my previous PR left two small mistakes:
- when printing epoch numbers I was doing "i_epoch/i_epoch" instead of "i_epoch/n_epoch"
- if verbosity was 0 the return value of `mx.fit` was `false`, otherwise it was an implicit nothing -- now it is always nothing.
=> BUG: fix two small mistakes with verbosity control

deps/build.jl
Here are the changes to support windows. With this `Pkg.build("MXNet")` should work. Since the version https://github.com/dmlc/mxnet/releases/tag/20160531 does not include the changes in https://github.com/yajiedesign/mxnet/releases/tag/20161125, the download is being performed twice. Let me know if there is a better way to address this.
=> Update build.jl to support windows

src/MXNet.jl, src/executor-group.jl, src/executor.jl, src/io.jl, src/module/Module.jl, src/module/symbol_module.jl, test/test-module.jl, test/unittest/symbol-module.jl
This pr is still work in progress, and since my knowledge of julia is rather limited, will be glad to change code in julian way.
This pr has following main features:
1. Fixed small bugs in original PR, so it now compiles.
2. Made tests for symbol module in unittest directory, and changed accordingly original test-module.jl. So, tests now are running from runtest as usual, and one can run only symbol module tests with `julia test-module.jl`
3. Prototype implementation of executor group, which is a mixture of port of python code and some parts were borrowed from `FeedForward` model.
4. Removed partially `Nullable`. Main idea, that in most cases it is enough to have an empty vector, so `isnull` check is excessive. It is important, though, to have `fixed_param_names` as `Nullable`, because in …
=> Executor Group and bugfixes

deps/build.jl
`wget` was failing to download mxnet.json , so replaced them with `Invoke-WebRequest`. After this change, MXNet.jl works on Windows, `Pkg.test("MXNet")` passes too.
Tested on
1) Windows Server 2012
2) Windows server 2008 SP1, R2
=> Using WebRequest function to download the JSON file

.travis.yml, examples/char-lstm/seq-data.jl, examples/char-lstm/train.jl, examples/mnist/mlp-test.jl, src/MXNet.jl, src/model.jl, test/unittest/kvstore.jl
We currently don't handle broadcasting gracefully and while I originally thought that we are just missing out on broadcasting functionality, it turns out that the deprecation of `.+` etc breaks a lot more code than expected.
This should turn Travis green again.
=> Disable Travis testing on v0.6 until #170 is addressed.

src/executor-group.jl, src/io.jl, src/module/Module.jl, src/module/sequential_module.jl, src/module/symbol_module.jl, test/test-module.jl, test/unittest/sequential-module.jl, test/unittest/symbol-module.jl
This is somewhat pre alpha implementation of SequentialModule (a.k.a Pipeline Module). Havn't tested it fully yet, suppose it's time to cover with tests and docs. So this PR is mainly for review.
What has been done:
1. Some tests restructure - added new test file, `test-module.jl` now has the same structure as `runtests.jl`, except it covers only `*module.jl` files.
2. Had to restructure partially `bind` and `init_params`, because it quickly became hard to maintain these long arguments definition. I am afraid it's a mess of dispatch calls now :-(
3. Tested up to `bind`.
Current problems: 
1. I am not very happy with current syntax. For example, existence of default `label_names` in `SymbolModule` means, that one has to remove them explicitly in every new layer declaration.
2. Also usage …
=> Sequential module

examples/char-lstm/lstm.jl, examples/char-lstm/sampler.jl, examples/char-lstm/seq-data.jl, src/optimizer.jl, src/symbolic-node.jl
This is fix of symbolic node inspired by issue https://github.com/dmlc/MXNet.jl/issues/197.
The main idea is that all SymbolicNode operators which require positional arguments do not have keyword arguments that uses SymbolicNode:
* `Crop`
* `Concat`
* `ElementWiseSum`
* `UpSampling`
* arithmetic operations
All other operators have `data` as one of the arguments and this is the only argument that is used as positional, in `@mx.chain` for example.
Also removed some deprecation warnings and fixed bug in `optimizer`
=> Fix for symbolic node

src/io.jl
Works around #205 most likely explanation is that subtyping went off the rails...
=> fix conflict with Images

src/metric.jl, test/unittest/metric.jl
`_update_single_output` needs to be type-stable, therefore move `@nd_as_jl` over the function barrier
=> Improve type-stability for metrices

deps/build.jl
This was always passing `-j1`, and after building this package a few times today, I'd really like it to use all my cores.  :)
=> Use `Sys.CPU_CORES` not `nprocs()` when doing a parallel `make`

deps/build.jl
Some machines return a non-zero pointer for `Libdl.dlopen("")` causing
MXNet dep build to incorrectly report presence of CUDA libraries.
This is possibly a bug in Julia - I'm not sure where the non-NULL pointer goes :)
=> Add extra check on CUDA library detection

deps/build.jl, src/base.jl
=> base/build: using `Libdl.dlext` for searching lib

deps/build.jl
Blocker PR: ~#267~, #271 (travis stuff)
---
I got this warning message before this PR
```c
In file included from src/operator/tensor/./../linalg.h:31:0,                                                          
from src/operator/tensor/./la_op_inline.h:27,                                                         
from src/operator/tensor/la_op.cc:25:                                                                 
src/operator/tensor/./.././c_lapack_api.h:245:25: note: #pragma message: Warning: lapack usage not enabled, linalg-ope$ators will not be available. Ensure that lapack library is installed and build with USE_LAPACK=1 to get lapack functio$
alities.                                                                                                               
" functionalities.") …
```
=> build: force enable LAPACK when Julia's OpenBLAS is available

src/ndarray.jl, test/unittest/ndarray.jl
https://github.com/apache/incubator-mxnet/blob/470b56437290b33fef51b067c96fdce08cefa584/include/mxnet/c_api.h#L516
seems we have it on `SymbolicNode` already, but `NDArray` not.
=> deepcopy on NDArray

NEWS.md, src/MXNet.jl, src/deprecated.jl, src/ndarray.jl, test/unittest/ndarray.jl
```julia
julia> x = mx.zeros(3, 4)
julia> y = mx.reshape(x, shape=(4, 3)) 
mx.NDArray{Float32}(3, 4)         
julia> size(y)
(3, 4)
julia> copy(y) 
3×4 Array{Float32,2}:   
0.0  0.0  0.0  0.0 
0.0  0.0  0.0  0.0
0.0  0.0  0.0  0.0
```
=> reshape on NDArray not working?

src/symbolic-node.jl, test/unittest/symbolic-node.jl
Ref: https://github.com/apache/incubator-mxnet/blob/470b56437290b33fef51b067c96fdce08cefa584/include/mxnet/c_api.h#L933
example: 
```julia
julia> print(mx.dot(mx.Variable(:x), mx.Variable(:y)))
Symbol Outputs:
output[0]=dot4(0)
Variable:y
Variable:x
--------------------
Op:dot, Name=dot4
Inputs:
arg[0]=y(0) version=0
arg[1]=x(0) version=0
```
=> sym-node: support `print` for debugging

src/ndarray.jl, test/unittest/ndarray.jl
Leverage `Base.showarray`.
e.g.
```julia
julia> mx.rand(0, 1, (5, 20))
5x20 mx.NDArray{Float32} @ CPU0:
0.628982    0.425452  0.952792  …  0.785153  0.181631
5.53504f-5  0.798047  0.45613      0.984329  0.0639553
0.872651    0.885338  0.687488     0.28173   0.512393
0.31186     0.185636  0.483409     0.703495  0.485628
0.273542    0.679879  0.215508     0.58641   0.580447
```
=> ndarray: pretty printing
