- README.md
Fixes an issue with `joinpath`.
> fixed joinpath problem in example in README.md

- src/optimizer.jl
- src/optimizers/adam.jl
This adds the ADAM SGD algorithm.
I am decaying the rate manually in the ADAM functions, as I was not sure how to integrate it properly with the other MXNet learning rate functions.
> added ADAM SGD

- .travis.yml
- README.md
- test/travis/run_coverage.sh
> Add coverage with Codecov.io

- .travis.yml
Hopefully fixes the travis builds on Linux
> add libatlas-base for cblas

- docs/api/io.rst
- docs/api/metric.rst
- docs/api/symbolic-node.rst
- src/metric.jl
Handling multi_output is a bit tricky because the inxed for the softmax output is inbetween the index for sample and the dimensions.
> [RFC] reformultate accuracy with multi_output in mind

- src/initializer.jl
~Small fixup for Xavier~
This now implements a set of different variants. The one I don't know where it comes from is the original one (also used by the Python interface https://github.com/dmlc/mxnet/blob/bf988bf650daae4e7e6736221fa81e8443a45d5b/python/mxnet/initializer.py#L99). It was changed from the caffe_avg (3 /((in + out)/2) to 3 / (in +out) in https://github.com/dmlc/mxnet/commit/189fbc1b09d7f0d8ddbf6f41083911d04142a849 by @antinucleon )
If there isn't any good reason for having it I would suggest dropping it to minimize the options.
> Different Xaiver variants

- docs/api/initializer.rst
- docs/api/io.rst
- docs/api/symbolic-node.rst
- src/initializer.jl
;) at least that it is how it is known everywhere else.
> Rename Xaiver to Xavier

- src/optimizer.jl
Adds the `Inv` LearningRate scheduler from Mocha
> adds LearningRate.Inv from Mocha

- src/util.jl
This works better on windows. Unzip must be installed though: 
http://sourceforge.net/projects/gnuwin32/?source=typ_redirect
Maybe use one of the Julia zip packages?
> use download instead of wget

- src/callback.jl
- src/model.jl
Metric result added to the epoch callbacks.
> accuracy in callback #49

- src/MXNet.jl
Another function that MXNet.jl needs to import explicitly.
> MXNet exposes a transpose function

- src/metric.jl
This might be quite narrow to my use case, but for analysing segmentation network it is very helpful to see the error per class.
> adds MultiACE or ACE per class

- src/model.jl
This allows to train a smaller network and then load the weight into a second network which is based upon the previous.
> Pre-seed model from smaller model.

- src/model.jl
- src/symbolic-node.jl
Depends on https://github.com/dmlc/mxnet/pull/2072 in reference to https://github.com/dmlc/MXNet.jl/pull/91
Should `list_attr` be the shallow version?
> add support for ListAttrShallow

- src/model.jl
I need to add tests for this, but this should fix the intermediate problem.
> fix overseen typo

- src/metric.jl
This adds a simple metric that can be used to combine multiple metrics to see MSE and logloss at once.
@pluskid Ideas on how to test this?
> add MultiMetric and reorder metric docs and update ACE and MultiACE for 1d labels

- src/io.jl
- src/ndarray.jl
- src/symbolic-node.jl
This solves one of my longer gripes that the docs where associated with the bindings instead of the methods.
> method docs

- REQUIRE
Thanks @tkelman for noticing this
> remove mistaken + in REQUIRE

- deps/build.jl
This cleans the buildscript a bit up.
@pluskid This should definitely run through the CI first. I tested it locally against prebuild versions of Julia, but I am not a 100% sure that `MakeTargets` works as I expect.
> improve buildscript

- deps/build.jl
The problem is that we need to specify `MSHADOW_LDFLAGS` and
`MSHADOW_CFLAGS`. The way MXNet is currently setup we can't change these
from the terminal. This solves the problem by using `sed` to change
`mshadow/make/mshadow.mk`. But if mshadow would change git could throw
an error on updating. So we remove the changes before an update and add
them afterwards again. This has the drawback that users can't modifty
that file. (But those users should maintain their own build and use
`MXNET_HOME`.)
This also eagerly deletes `usr/lib/libmxnet.so` So that we actually
trigger a rebuild on an update of the pkg.
The travis build for this can be found at https://travis-ci.org/vchuravy/MXNet.jl/builds/158598024
> Fixes deps/build.jl on Travis

- examples/regression-example.jl
simple MLP for regression, illustrates data provision from memory, and how to obtain fits
> add example of simple MLP for regression

- deps/build.jl
Fixes #143 
I haven't done to much testing on this and so let's wait with merging this till I got around to that.
> try to automatically find CUDA

- src/visualize.jl
- test/unittest/visualize.jl
Fixed change from `param` to `attr` in function `to_graphviz`, plus added small test.
> Fixed visualize

- src/model.jl
This adds another option to `TrainingOptions` to control the verbosity of printed messages during training.
The default behavior hasn't changed.
I made fairly arbitrary decisions regarding what the cutoffs were for verbosity levels `n` and `n+1`, so if anyone has comments on how that can be improved I'm all ears.
> ENH: added verbosity training option to control printouts

- src/ndarray.jl
- test/unittest/ndarray.jl
Fixed conversion of julia params to libmxnet. Added more tests in test/ndarray.jl
> Fix scalar operations in NDArray

- deps/build.jl
This addresses #184, #180.
Essentially this allows us to download the latest prebuilt-binaries for windows on master and keep to a good version on tagged releases.
> refactor windows support

- REQUIRE
- test/runtests.jl
- test/unittest/bind.jl
- test/unittest/io.jl
- test/unittest/kvstore.jl
- test/unittest/name.jl
- test/unittest/ndarray.jl
- test/unittest/operator.jl
- test/unittest/random.jl
- test/unittest/symbolic-node.jl
- test/unittest/visualize.jl
addresses the review comments by Tony in https://github.com/JuliaLang/METADATA.jl/pull/7699#discussion_r98325245
> remove BaseTestNext and bump Compat

- deps/build.jl
- src/base.jl
addresses @tkelman comment in https://github.com/dmlc/MXNet.jl/pull/194#issuecomment-275901350
If this is ok I will merge asap and put out a new patch release.
> remove usr/setupenv.cmd because it is too invasive

- docs/src/tutorial/mnist.md
Removed the key for the data attribute to match examples.
> Fixed data attribute

- src/callback.jl
> docs: update renamed `every_n_batch`

- src/visualize.jl
> Check if key stride exists in the node info when producing graphviz output

- src/initializer.jl
- test/unittest/initializer.jl
x-ref: https://github.com/dmlc/MXNet.jl/pull/223#issuecomment-293745376
@facundoq Can you double check that this is correct?
I wonder why we never merged the initialisier part of #34 (quite odd).
> fixes bilinear initializer following approach in #34

- src/ndarray.jl
adapts to changes in  dmlc/mxnet#5629
> fix pointer(NDArray) for Float64

- src/metric.jl
I am working on cleaning up #224 and splitting it up into PRs that are independent from each other.
fixes #229
> SeqMetric and NullMetric

- .travis.yml
- XCode8 supports thread_local in C++
> Fix mac travis

- src/model.jl
Resolves #243 
I've set the default behavior to `verbosity=1` which is the same as the previous behavior, but I'd also be happy with verbosity=0 by default. It's up to you.
> Verbosity option in predict()

- appveyor.yml
@pluskid can you enable appveyor on MXNet.jl?
Fixes: #191
> update appveyor script

- appveyor.yml
- deps/build.jl
- docs/src/user-guide/install.md
This is a quality of life improvement to our libmxnet build process. I have tested this on my local Linux box, but I would appreciate wider testing (especially on Windows)
Fixes: #175, #143
> Improve GPU detection

- .travis.yml
- NEWS.md
- README.md
- appveyor.yml
- deps/build.jl
- docs/mkdocs.yml
- docs/src/tutorial/mnist.md
- docs/src/user-guide/install.md
- examples/char-lstm/lstm.jl
- examples/char-lstm/sampler.jl
- examples/char-lstm/seq-data.jl
- examples/mnist/lenet-stn.jl
- examples/regression-example.jl
- src/base.jl
- src/callback.jl
- src/initializer.jl
- src/io.jl
- src/metric.jl
- src/model.jl
- src/ndarray.jl
- src/optimizer.jl
- src/symbolic-node.jl
- src/util.jl
- src/visualize.jl
- test/unittest/initializer.jl
- test/unittest/metric.jl
- test/unittest/symbolic-node.jl
I am prepping a new release of MXNet.jl
TODO:
> Preparing release v0.2.2

- deps/build.jl
tag: https://github.com/apache/incubator-mxnet/releases/tag/0.11.0
> build: bump curr_win to 20170819, MXNet 0.11.0

- src/ndarray.jl
Ref:
* https://github.com/dmlc/mshadow/pull/244
* https://github.com/dmlc/mshadow/pull/258
> ndarray: add kInt8 and kInt64 into TypeFlag enum

- .travis.yml
- deps/build.jl
* change # of make jobs in order to prevent from out-of-memory issue
* travis_wait is a workaround about
https://github.com/JuliaLang/julia/pull/23601
> travis : set make -j4 and travis_wait

- deps/build.jl
resovle: https://github.com/dmlc/MXNet.jl/pull/269#issuecomment-328529401
> build: fix macOS LAPACK build

- deps/build.jl
* remove FileRule on config.mk, we always override it.
Due to the following workflow is quite common:
* user issue `Pkg.build("MXNet")`
* then, build failed because the `CUDA_HOME` not set properly.
* if the `FileRule` find `config.mk`,
re-issuing `Pkg.build` won't change `config.mk`.
User need to delete/modify `config.mk` manually
* fix CUDA config
* the build_steps didn't being unfolded correctly.
* consider following cases:
```julia
@build_steps begin
if true
`1`
`2`
`3`
if true
`42`
end
end
end
BinDeps.SynchronousStepCollection(Any[`42`], "", "")
```
vs
```julia
@build_steps begin
if true
@build_steps begin
`1`
`2`
`3`
if true
`42`
end
end  # inner build_steps
end  # if
end
BinDeps.SynchronousStepCollection(Any[`1`, `2`, `3`, `42`], "", "")
```
> build: remove FileRule on config.mk and fix CUDA config

- src/base.jl
- src/executor.jl
https://github.com/apache/incubator-mxnet/blob/fd201d4a5b1e4c32345f5799c7a0a79c284567bb/include/mxnet/op_attr_types.h#L43-L57
will work on this after #281
> update OpReqType enum

- deps/build.jl
https://github.com/apache/incubator-mxnet/blob/master/make/config.mk#L58
Blocker: ~#275~
> build with CuDNN support

- NEWS.md
- src/deprecated.jl
- src/symbolic-node.jl
- test/unittest/symbolic-node.jl
> sym-node: implement reshape api as Base

- src/random.jl
Ref: https://github.com/apache/incubator-mxnet/pull/7939
> random: upstream api change

- NEWS.md
- src/deprecated.jl
- src/random.jl
- test/unittest/random.jl
> random: rename srand! to srand

- src/base.jl
- test/runtests.jl
- Ref: https://github.com/apache/incubator-mxnet/pull/8013
> base: support MXGetVersion

- deps/build.jl
- change ADD_LDFLAGS
- https://github.com/apache/incubator-mxnet/pull/7856
- https://github.com/apache/incubator-mxnet/pull/7838
- guessing the CUDA_HOME if user not provides it.
----
@SimonEnsemble
Could you try this patch out with a clean clone?
> build: improve cuda detection

- NEWS.md
- src/ndarray.jl
- test/unittest/ndarray.jl
e.g.
```julia
1 ./ mx.NDArray(Float32[1 2; 3 4])
```
> ndarray: implement rdiv

- NEWS.md
- src/ndarray.jl
- test/unittest/ndarray.jl
> ndarray: regularize fill! API
